/* ★ 배포판 — local 영상 경로를 비웠다(GitHub Pages 에 2.5GB 를 못 올린다).
   web 이 채워진 편만 재생된다. 만든 도구: 배포꾸리기.py */
/* 강의 영상 — 임팩트판\사이트영상.py 가 만든다. 리프 코드 하나에 영상 하나.
 * 2026-09-18: 2학기 중간 범위 새 강의(임팩트판)를 유튜브 일부 공개로 올리고 잇는다. yt 가 있으면 skilltree 가 유튜브로 튼다.
 * 올린 편 21개 · 리프 32개. 옛 목록은 js/_video_폐기전.js.bak */
window.VIDEO={
 "F2.1": {
  "title": "기본권의 다섯 유형",
  "min": 5.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/4-S3AhRD86Q",
  "yt": "4-S3AhRD86Q",
  "mb": 197,
  "part": 1,
  "parts": 1,
  "ep": "F01"
 },
 "F2.3": {
  "title": "기본권의 제한과 한계",
  "min": 4.3,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/a2bU6E7uhR4",
  "yt": "a2bU6E7uhR4",
  "mb": 148,
  "part": 1,
  "parts": 1,
  "ep": "F02"
 },
 "F1.1": {
  "title": "인권의 의미와 특징 · 인권의 세대",
  "min": 1.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/QdFY-7whZwk",
  "yt": "QdFY-7whZwk",
  "mb": 60,
  "part": 1,
  "parts": 1,
  "ep": "F03"
 },
 "F1.3": {
  "title": "인권의 의미와 특징 · 인권의 세대",
  "min": 1.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/QdFY-7whZwk",
  "yt": "QdFY-7whZwk",
  "mb": 60,
  "part": 1,
  "parts": 1,
  "ep": "F03"
 },
 "F1.2": {
  "title": "인권 확장의 역사 · 현대의 새로운 인권",
  "min": 1.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/AtN-mHztoLc",
  "yt": "AtN-mHztoLc",
  "mb": 62,
  "part": 1,
  "parts": 1,
  "ep": "F04"
 },
 "F1.4": {
  "title": "인권 확장의 역사 · 현대의 새로운 인권",
  "min": 1.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/AtN-mHztoLc",
  "yt": "AtN-mHztoLc",
  "mb": 62,
  "part": 1,
  "parts": 1,
  "ep": "F04"
 },
 "F2.4": {
  "title": "인권 보장을 위한 헌법의 역할",
  "min": 6.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/XXVH738j1cE",
  "yt": "XXVH738j1cE",
  "mb": 242,
  "part": 1,
  "parts": 1,
  "ep": "F05"
 },
 "F3.1": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/N-RIc7tEfxE",
  "yt": "N-RIc7tEfxE",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.2": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/N-RIc7tEfxE",
  "yt": "N-RIc7tEfxE",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.3": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/N-RIc7tEfxE",
  "yt": "N-RIc7tEfxE",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.4": {
  "title": "법원과 사법권의 독립",
  "min": 5.0,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/xyFDZpma7VM",
  "yt": "xyFDZpma7VM",
  "mb": 165,
  "part": 1,
  "parts": 1,
  "ep": "F07"
 },
 "F3.5": {
  "title": "헌법재판소 · 위헌 법률 심판과 헌법 소원",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/le8Ehcnr_2c",
  "yt": "le8Ehcnr_2c",
  "mb": 187,
  "part": 1,
  "parts": 1,
  "ep": "F08"
 },
 "F4.1": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/y9n_6d2K2pE",
  "yt": "y9n_6d2K2pE",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "F4.2": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/y9n_6d2K2pE",
  "yt": "y9n_6d2K2pE",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "F3.6": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/y9n_6d2K2pE",
  "yt": "y9n_6d2K2pE",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "G1.1": {
  "title": "정의의 의미와 분배적 정의",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/YAZ-xREVnm4",
  "yt": "YAZ-xREVnm4",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "G01"
 },
 "G1.2": {
  "title": "정의의 의미와 분배적 정의",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/YAZ-xREVnm4",
  "yt": "YAZ-xREVnm4",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "G01"
 },
 "G1.3": {
  "title": "교정적 정의 · 응보주의와 예방주의",
  "min": 7.5,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/1iPypcvF9hM",
  "yt": "1iPypcvF9hM",
  "mb": 265,
  "part": 1,
  "parts": 1,
  "ep": "G02"
 },
 "G2.1": {
  "title": "자유주의적 정의관과 공동체주의적 정의관",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/Ro2kL94Mw70",
  "yt": "Ro2kL94Mw70",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G03"
 },
 "G2.2": {
  "title": "자유주의적 정의관과 공동체주의적 정의관",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/Ro2kL94Mw70",
  "yt": "Ro2kL94Mw70",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G03"
 },
 "G3.1": {
  "title": "사회 계층의 양극화와 사회적 약자 차별",
  "min": 5.1,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/v43IHsLme6I",
  "yt": "v43IHsLme6I",
  "mb": 179,
  "part": 1,
  "parts": 1,
  "ep": "G04"
 },
 "G3.3": {
  "title": "사회 계층의 양극화와 사회적 약자 차별",
  "min": 5.1,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/v43IHsLme6I",
  "yt": "v43IHsLme6I",
  "mb": 179,
  "part": 1,
  "parts": 1,
  "ep": "G04"
 },
 "G3.2": {
  "title": "공간 불평등 · 성장 거점 개발과 수도권 집중",
  "min": 4.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/OT9NZEQ_Lrg",
  "yt": "OT9NZEQ_Lrg",
  "mb": 181,
  "part": 1,
  "parts": 1,
  "ep": "G05"
 },
 "G3.4": {
  "title": "정의로운 사회를 위한 제도 · 복지와 적극적 평등 실현 조치",
  "min": 7.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/-u8KG191iAo",
  "yt": "-u8KG191iAo",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G06"
 },
 "I1.1": {
  "title": "세계화의 양상 · 세계 도시와 다국적 기업",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/Y7uwY132TvY",
  "yt": "Y7uwY132TvY",
  "mb": 290,
  "part": 1,
  "parts": 1,
  "ep": "I01"
 },
 "I1.2": {
  "title": "세계화의 양상 · 세계 도시와 다국적 기업",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/Y7uwY132TvY",
  "yt": "Y7uwY132TvY",
  "mb": 290,
  "part": 1,
  "parts": 1,
  "ep": "I01"
 },
 "I2.1": {
  "title": "국제 갈등과 세계의 주요 분쟁 지역",
  "min": 4.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/tBRB3QrYQdM",
  "yt": "tBRB3QrYQdM",
  "mb": 178,
  "part": 1,
  "parts": 1,
  "ep": "I02"
 },
 "I2.2": {
  "title": "국제 사회의 행위 주체",
  "min": 5.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/7Z6gT2b9RiY",
  "yt": "7Z6gT2b9RiY",
  "mb": 203,
  "part": 1,
  "parts": 1,
  "ep": "I03"
 },
 "I2.3": {
  "title": "국제 사회의 행위 주체",
  "min": 5.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/7Z6gT2b9RiY",
  "yt": "7Z6gT2b9RiY",
  "mb": 203,
  "part": 1,
  "parts": 1,
  "ep": "I03"
 },
 "I3.1": {
  "title": "소극적 평화와 적극적 평화",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/h4QzUslMhwY",
  "yt": "h4QzUslMhwY",
  "mb": 258,
  "part": 1,
  "parts": 1,
  "ep": "I04"
 },
 "I3.2": {
  "title": "남북 분단과 동아시아의 역사 갈등",
  "min": 6.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/9as5gJdAwpg",
  "yt": "9as5gJdAwpg",
  "mb": 247,
  "part": 1,
  "parts": 1,
  "ep": "I05"
 },
 "I3.3": {
  "title": "남북 평화 통일과 우리나라의 역할",
  "min": 6.2,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/gah0iSf4BwE",
  "yt": "gah0iSf4BwE",
  "mb": 227,
  "part": 1,
  "parts": 1,
  "ep": "I06"
 }
};
