/* ★ 배포판 — local 영상 경로를 비웠다(GitHub Pages 에 2.5GB 를 못 올린다).
   web 이 채워진 편만 재생된다. 만든 도구: 배포꾸리기.py */
/* 강의 영상 — 임팩트판\사이트영상.py 가 만든다. 리프 코드 하나에 영상 하나.
 * 2026-09-18: 2학기 중간 범위 새 강의(임팩트판)를 유튜브 일부 공개로 올리고 잇는다. yt 가 있으면 skilltree 가 유튜브로 튼다.
 * 올린 편 21개 · 리프 32개. 옛 목록은 js/_video_폐기전.js.bak */
window.VIDEO={
 "F2.1": {
  "title": "기본권의 다섯 유형",
  "min": 5.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/ltNe5kFNjTE",
  "yt": "ltNe5kFNjTE",
  "mb": 197,
  "part": 1,
  "parts": 1,
  "ep": "F01"
 },
 "F2.3": {
  "title": "기본권의 제한과 한계",
  "min": 4.3,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/xEu5njmfl0c",
  "yt": "xEu5njmfl0c",
  "mb": 148,
  "part": 1,
  "parts": 1,
  "ep": "F02"
 },
 "F1.1": {
  "title": "인권의 의미와 특징 · 인권의 세대",
  "min": 1.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/sBrqbMD0yvQ",
  "yt": "sBrqbMD0yvQ",
  "mb": 60,
  "part": 1,
  "parts": 1,
  "ep": "F03"
 },
 "F1.3": {
  "title": "인권의 의미와 특징 · 인권의 세대",
  "min": 1.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/sBrqbMD0yvQ",
  "yt": "sBrqbMD0yvQ",
  "mb": 60,
  "part": 1,
  "parts": 1,
  "ep": "F03"
 },
 "F1.2": {
  "title": "인권 확장의 역사 · 현대의 새로운 인권",
  "min": 1.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/eqF5zhho8yQ",
  "yt": "eqF5zhho8yQ",
  "mb": 62,
  "part": 1,
  "parts": 1,
  "ep": "F04"
 },
 "F1.4": {
  "title": "인권 확장의 역사 · 현대의 새로운 인권",
  "min": 1.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/eqF5zhho8yQ",
  "yt": "eqF5zhho8yQ",
  "mb": 62,
  "part": 1,
  "parts": 1,
  "ep": "F04"
 },
 "F2.4": {
  "title": "인권 보장을 위한 헌법의 역할",
  "min": 6.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/vuCT65ePd5s",
  "yt": "vuCT65ePd5s",
  "mb": 242,
  "part": 1,
  "parts": 1,
  "ep": "F05"
 },
 "F3.1": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/CV7fVbwAvok",
  "yt": "CV7fVbwAvok",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.2": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/CV7fVbwAvok",
  "yt": "CV7fVbwAvok",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.3": {
  "title": "권력 분립 · 국회와 대통령",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/CV7fVbwAvok",
  "yt": "CV7fVbwAvok",
  "mb": 185,
  "part": 1,
  "parts": 1,
  "ep": "F06"
 },
 "F3.4": {
  "title": "법원과 사법권의 독립",
  "min": 5.0,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/BBFAF_kLicc",
  "yt": "BBFAF_kLicc",
  "mb": 165,
  "part": 1,
  "parts": 1,
  "ep": "F07"
 },
 "F3.5": {
  "title": "헌법재판소 · 위헌 법률 심판과 헌법 소원",
  "min": 5.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/ITsf8n8KQNU",
  "yt": "ITsf8n8KQNU",
  "mb": 187,
  "part": 1,
  "parts": 1,
  "ep": "F08"
 },
 "F4.1": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/5IHQp_pi7QQ",
  "yt": "5IHQp_pi7QQ",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "F4.2": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/5IHQp_pi7QQ",
  "yt": "5IHQp_pi7QQ",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "F3.6": {
  "title": "시민 참여와 시민 불복종",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/5IHQp_pi7QQ",
  "yt": "5IHQp_pi7QQ",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "F09"
 },
 "G1.1": {
  "title": "정의의 의미와 분배적 정의",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/vfMeJ6xrkGw",
  "yt": "vfMeJ6xrkGw",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "G01"
 },
 "G1.2": {
  "title": "정의의 의미와 분배적 정의",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/vfMeJ6xrkGw",
  "yt": "vfMeJ6xrkGw",
  "mb": 260,
  "part": 1,
  "parts": 1,
  "ep": "G01"
 },
 "G1.3": {
  "title": "교정적 정의 · 응보주의와 예방주의",
  "min": 7.5,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/rJj97jDOOu8",
  "yt": "rJj97jDOOu8",
  "mb": 265,
  "part": 1,
  "parts": 1,
  "ep": "G02"
 },
 "G2.1": {
  "title": "자유주의적 정의관과 공동체주의적 정의관",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/R_rJGFIqwcQ",
  "yt": "R_rJGFIqwcQ",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G03"
 },
 "G2.2": {
  "title": "자유주의적 정의관과 공동체주의적 정의관",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/R_rJGFIqwcQ",
  "yt": "R_rJGFIqwcQ",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G03"
 },
 "G3.1": {
  "title": "사회 계층의 양극화와 사회적 약자 차별",
  "min": 5.1,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/bmM6rYGP6AU",
  "yt": "bmM6rYGP6AU",
  "mb": 179,
  "part": 1,
  "parts": 1,
  "ep": "G04"
 },
 "G3.3": {
  "title": "사회 계층의 양극화와 사회적 약자 차별",
  "min": 5.1,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/bmM6rYGP6AU",
  "yt": "bmM6rYGP6AU",
  "mb": 179,
  "part": 1,
  "parts": 1,
  "ep": "G04"
 },
 "G3.2": {
  "title": "공간 불평등 · 성장 거점 개발과 수도권 집중",
  "min": 4.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/YKuaco46wa4",
  "yt": "YKuaco46wa4",
  "mb": 181,
  "part": 1,
  "parts": 1,
  "ep": "G05"
 },
 "G3.4": {
  "title": "정의로운 사회를 위한 제도 · 복지와 적극적 평등 실현 조치",
  "min": 7.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/Mf4xVsR-DmU",
  "yt": "Mf4xVsR-DmU",
  "mb": 278,
  "part": 1,
  "parts": 1,
  "ep": "G06"
 },
 "I1.1": {
  "title": "세계화의 양상 · 세계 도시와 다국적 기업",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/xQFZO4hcfpo",
  "yt": "xQFZO4hcfpo",
  "mb": 290,
  "part": 1,
  "parts": 1,
  "ep": "I01"
 },
 "I1.2": {
  "title": "세계화의 양상 · 세계 도시와 다국적 기업",
  "min": 7.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/xQFZO4hcfpo",
  "yt": "xQFZO4hcfpo",
  "mb": 290,
  "part": 1,
  "parts": 1,
  "ep": "I01"
 },
 "I2.1": {
  "title": "국제 갈등과 세계의 주요 분쟁 지역",
  "min": 4.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/5EzKxqcmzX0",
  "yt": "5EzKxqcmzX0",
  "mb": 178,
  "part": 1,
  "parts": 1,
  "ep": "I02"
 },
 "I2.2": {
  "title": "국제 사회의 행위 주체",
  "min": 5.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/PPEXyer9-Zc",
  "yt": "PPEXyer9-Zc",
  "mb": 203,
  "part": 1,
  "parts": 1,
  "ep": "I03"
 },
 "I2.3": {
  "title": "국제 사회의 행위 주체",
  "min": 5.8,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/PPEXyer9-Zc",
  "yt": "PPEXyer9-Zc",
  "mb": 203,
  "part": 1,
  "parts": 1,
  "ep": "I03"
 },
 "I3.1": {
  "title": "소극적 평화와 적극적 평화",
  "min": 7.6,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/a9RqLABfq6Y",
  "yt": "a9RqLABfq6Y",
  "mb": 258,
  "part": 1,
  "parts": 1,
  "ep": "I04"
 },
 "I3.2": {
  "title": "남북 분단과 동아시아의 역사 갈등",
  "min": 6.9,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/vqI-EaEg_bg",
  "yt": "vqI-EaEg_bg",
  "mb": 247,
  "part": 1,
  "parts": 1,
  "ep": "I05"
 },
 "I3.3": {
  "title": "남북 평화 통일과 우리나라의 역할",
  "min": 6.2,
  "sum": "",
  "local": "",
  "web": "https://youtu.be/siX5UiF22OI",
  "yt": "siX5UiF22OI",
  "mb": 227,
  "part": 1,
  "parts": 1,
  "ep": "I06"
 }
};
